{
 "title": "01 - Servidor OK - porteira-server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU - porteira-server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "group": { "filter": "/.*/" },
     "host": { "filter": "porteira-server" },
     "item": { "filter": "CPU utilization" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "schema": 12
    }
   ]
  },
  {
   "title": "Memoria disponivel - porteira-server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "group": { "filter": "/.*/" },
     "host": { "filter": "porteira-server" },
     "item": { "filter": "Available memory in %" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "schema": 12
    }
   ]
  },
  {
   "title": "Load average (1 min) - porteira-server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "/.*/" },
     "host": { "filter": "porteira-server" },
     "item": { "filter": "Load average (1m avg)" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "schema": 12
    }
   ]
  },
  {
   "title": "CPU atual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "group": { "filter": "/.*/" },
     "host": { "filter": "porteira-server" },
     "item": { "filter": "CPU utilization" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "schema": 12
    }
   ]
  },
  {
   "title": "Memoria disponivel atual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "group": { "filter": "/.*/" },
     "host": { "filter": "porteira-server" },
     "item": { "filter": "Available memory in %" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "schema": 12
    }
   ]
  },
  {
   "title": "Load atual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "/.*/" },
     "host": { "filter": "porteira-server" },
     "item": { "filter": "Load average (1m avg)" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "schema": 12
    }
   ]
  }
 ]
}