{
 "title": "03 - Visao operacional - tudo UP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tudo verde - API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"checkout-api\"}",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Pressao - p95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(checkout_http_request_duration_seconds_bucket{path=\"/checkout\"}[1m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Sintoma - erros",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(checkout_errors_total[15m]))",
     "legendFormat": "erros"
    }
   ]
  },
  {
   "title": "Evidencia - pool waiting",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(checkout_db_pool_waiting[15m])",
     "legendFormat": "max waiting"
    }
   ]
  },
  {
   "title": "A jornada do usuario",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(checkout_http_requests_total{path=\"/checkout\",status=\"200\"}[1m]))",
     "legendFormat": "sucesso/s"
    },
    {
     "expr": "sum(rate(checkout_http_requests_total{path=\"/checkout\",status=\"503\"}[1m]))",
     "legendFormat": "falha/s"
    }
   ]
  },
  {
   "title": "O que explica a experiencia",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(checkout_http_request_duration_seconds_bucket{path=\"/checkout\"}[1m])))",
     "legendFormat": "p95"
    },
    { "expr": "checkout_db_pool_waiting", "legendFormat": "pool waiting" }
   ]
  },
  {
   "title": "Logs que contam a historia",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"api-up\"} |~ \"database_pool_ready|db_pool_exhausted|checkout_failed\""
    }
   ]
  }
 ]
}