apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: db:5432
    user: $__env{APP_DB_USER}
    jsonData:
      database: $__env{APP_DB_NAME}
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    secureJsonData:
      password: $__env{APP_DB_PASSWORD}
  - name: Zabbix
    uid: dfyxo4mmoy8lce
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: https://zabbix-ps.joaoxavier.app.br/api_jsonrpc.php
