#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:5055}"
PROMETHEUS_RW_URL="${PROMETHEUS_RW_URL:-http://localhost:9090/api/v1/write}"
PROMETHEUS_RW_TREND_STATS="${PROMETHEUS_RW_TREND_STATS:-p(50),p(90),p(95),avg,min,max}"
GRADUAL_START_VUS="${GRADUAL_START_VUS:-4}"
GRADUAL_MAX_VUS="${GRADUAL_MAX_VUS:-22}"
GRADUAL_START_DURATION="${GRADUAL_START_DURATION:-2m}"
GRADUAL_STEP_DURATION="${GRADUAL_STEP_DURATION:-1m}"
K6_TEST_ID="${K6_TEST_ID:-gradual-checkout}"

if command -v k6 >/dev/null 2>&1; then
  exec env BASE_URL="$BASE_URL" GRADUAL_START_VUS="$GRADUAL_START_VUS" GRADUAL_MAX_VUS="$GRADUAL_MAX_VUS" GRADUAL_START_DURATION="$GRADUAL_START_DURATION" GRADUAL_STEP_DURATION="$GRADUAL_STEP_DURATION" K6_TEST_ID="$K6_TEST_ID" K6_PROMETHEUS_RW_SERVER_URL="$PROMETHEUS_RW_URL" K6_PROMETHEUS_RW_TREND_STATS="$PROMETHEUS_RW_TREND_STATS" k6 run -o experimental-prometheus-rw load/gradual.js
fi

if command -v docker >/dev/null 2>&1; then
  exec docker run --rm --network host -e BASE_URL="$BASE_URL" -e GRADUAL_START_VUS="$GRADUAL_START_VUS" -e GRADUAL_MAX_VUS="$GRADUAL_MAX_VUS" -e GRADUAL_START_DURATION="$GRADUAL_START_DURATION" -e GRADUAL_STEP_DURATION="$GRADUAL_STEP_DURATION" -e K6_TEST_ID="$K6_TEST_ID" -e K6_PROMETHEUS_RW_SERVER_URL="$PROMETHEUS_RW_URL" -e K6_PROMETHEUS_RW_TREND_STATS="$PROMETHEUS_RW_TREND_STATS" -i grafana/k6 run -o experimental-prometheus-rw - < load/gradual.js
fi

echo 'Instale k6 ou Docker para gerar carga gradual.' >&2
exit 1
